services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:2025.10.4"
    container_name: homeassistant
    network_mode: host
    volumes:
      - ./homeassistant_config:/config
    environment:
      - TZ=America/Argentina/Mendoza
    privileged: true
    restart: unless-stopped
